application:
  amqp:
    enabled: true
    admin.exchange: admin

  jwt:
    expire: 86400000
    secret: secret

  kub.services:
    pes: http://pes-service:9010/
    admin: http://admin-service:9006/
    acte: http://acte-service:9008/
    convoc: http://convocation-service:9012/

  migration:
    serverIP: 127.0.0.1
    serverUser: stela
    privateKeyPath: /ssh-keys/id_rsa
    publicKeyPath: /ssh-keys/id_rsa.pub
    privKeyPassphrase: passphrase
    mySQLUser: stela
    mySQLPassword: password
    mySQLPort: 3306
    database: stela

  certVerificationEnabled: true

  scheduling:
    enabled: true

  archiverCrons:
    archiveTask: "0 0 2 * * *"
    checkArchivesTask: "0 0 3 * * *"

  storage:
    importDelay: 60000
    awss3:
      region: eu-west-3
      bucket: bucket.stela.sictiam.fr
      accesskey: accesskey
      secretkey: secretkey
      cleaningCron: "0 0 0 * * *"
    filesystem:
      path: /tmp

  clamav:
    port: 3310
    host: clamav

logging:
  file: ./build/logs/${spring.application.name}.log
  level:
    root: INFO
    # Enable logging of access token request
    #org.apache.http.headers: DEBUG
    # Enable logging of binded parameters in SQL requests
    #org.hibernate.type: TRACE
    # Hides HHH000424: Disabling contextual LOB creation as createClob() method threw error
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: WARN
    org.springframework: INFO
    # Enable request logging
    org.springframework.web.filter: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.security.web.access: DEBUG
    fr.sictiam.stela: DEBUG
  filesize:
    max: 100MB
  archivesize:
    max: 10GB
  history:
    max: 60

spring:
  jackson.date-format: "yyyy-MM-dd HH:mm:ss"
  mail:
    host: smtp.gmail.com
    port: 587
    username: username
    password: password
    # see https://javaee.github.io/javamail/docs/api/com/sun/mail/smtp/package-summary.html
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          starttls.enable: true
  jpa:
    hibernate:
      ddl-auto: none
      # Enable logging of SQL statements
      #properties.hibernate:
      #show_sql: true
      #use_sql_comments: true
      #format_sql: true
      #type: TRACE
  flyway:
    baseline-on-migrate: true
    locations: classpath:/db/migration
  rabbitmq:
    host: rabbitmq
    username: test
    password: password
  servlet:
    multipart.max-file-size: 128MB
    multipart.max-request-size: 128MB
  output:
    ansi:
      enabled: ALWAYS

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

kernel:
  alt_uri: ${kernel.base_uri}
  auth:
    issuer: ${kernel.base_uri}/
    auth_endpoint: ${kernel.alt_uri}/a/auth
    token_endpoint: ${kernel.base_uri}/a/token
    keys_endpoint: ${kernel.base_uri}/a/keys
    userinfo_endpoint: ${kernel.base_uri}/a/userinfo
    password_change_endpoint: ${kernel.alt_uri}/a/password
    revoke_endpoint: ${kernel.base_uri}/a/revoke
    logout_endpoint: ${kernel.alt_uri}/a/logout
  organization_endpoint: ${kernel.base_uri}/d/org
  notifications_endpoint: ${kernel.base_uri}/n
  scopes_to_require: openid profile email
  